server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - logging.yml
      - monitoring.yml
      - redis.yml
      - kafka.yml


springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
  retry:
    retryAspectOrder: 2

resilience4j.circuitbreaker:
  instances:
    pgCircuit:
      sliding-window-size: 10
      failure-rate-threshold: 50       # 실패율이 50% 넘으면 Open
      wait-duration-in-open-state: 10s # Open 상태 유지 시간
      permitted-number-of-calls-in-half-open-state: 2
      slow-call-duration-threshold: 2s
      slow-call-rate-threshold: 50

resilience4j.retry:
  instances:
    pgRetry:
      maxAttempts: 2
      waitDuration: 1s
#      enableExponentialBackoff: true
#      exponentialBackoffMultiplier: 2
      retryExceptions:
        - com.loopers.infrastructure.http.payment.error.PgTransientException
        - feign.RetryableException         # 진짜 네트워크 실패도 재시도
      ignoreExceptions:
        - com.loopers.infrastructure.http.payment.error.PgBusinessException
      fail-after-max-attempts: true



---
spring:
  config:
    activate:
      on-profile: local, test


resilience4j.circuitbreaker:
  instances:
    pgCircuit:
      sliding-window-size: 6
      failure-rate-threshold: 50       # 실패율이 50% 넘으면 Open
      wait-duration-in-open-state: 200ms # Open 상태 유지 시간
      permitted-number-of-calls-in-half-open-state: 2
      slow-call-duration-threshold: 20ms
      slow-call-rate-threshold: 50

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false